[package]
name = "logchop"
version = "0.1.0"
authors = ["Aru Sahni <aru@arusahni.net>"]
license = "Apache-2.0"
license-file = "LICENSE.txt"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4"
paste = "1.0"

